### ISSUE TITLE
While true

### ISSUE THREAD

**Issue by matevzv** [jenkoj/resolvd#4]
V while true zanki moraš pazit na to kaj se zgodi v primeru da bi se konstantno zgodil except ker ni nobenega timeouta bi ta loop zasedel 100% CPU-ja

https://github.com/jenkoj/resolvd/blob/c89639dd67529e9c0bfd5b0c45e21bcaaa17c506/publish_measurements.py#L39

**Comment by jenkoj** [comment]
dobra opazka! bom dodal nek minimalen sleep.
